#!/usr/bin/env php
<?php
declare(strict_types=1);

//
// ORBITAL CLI
// https://github.com/orbital-framework
//
// Command:
// php orbital [command] ...
//
// Recommended cron mode:
// */5 * * * * php orbital [command] ... >> /logs/cron.log 2>&1
//

set_time_limit(0);

// Require app
require_once __DIR__. '/app/bootstrap.php';

// Run console command
\Orbital\Console\Command::run(
    \Orbital\Framework\Request::arg('1', NULL)
);