#!/usr/bin/env php
<?php
//
// ORBITAL CLI
// https://github.com/orbital-framework
//
// Command:
// php orbital ...
//
// Recommended cron mode:
// */5 * * * * php orbital ... >> /logs/cron.log 2>&1
//

set_time_limit(0);

// Require app
require_once __DIR__. '/app/bootstrap.php';

// Run console observer
Orbital\Framework\Observer::fire('consoleCommand');